#' @name add.names
#' 
#' @description a function to use the dictionary to assign row and column 
#'              names back to the gene expression matrix that has indexes as row
#'              and column names.
#'              
#' @param obs the gene expression matrix
#' @param dict_list a list. The dictionary list generated by get.dictionary function
#' @param row logical. Do you want rownames indexes to be replaced by their names? 
#'            Default TRUE.
#' @param col logical. Do you want colnames indexes to be replaced by their names? 
#'            Default TRUE.
#' 

add.names <- function(obs, dict_list, row = TRUE, col = TRUE) {
  ## Change row and column names in the obs object
  if (row) {
    rownames(obs) <-
      dict_list[["spots"]][match(rownames(obs), rownames(dict_list[["spots"]]))]
  }
  
  if (col) {
    colnames(obs) <-
      dict_list[["genes"]][match(colnames(obs), rownames(dict_list[["genes"]]))]
  }
  
  return(obs)
}