#' @name clean.no.nbs
#' 
#' @description a function that cleans a data frame which contains polygon 
#'              geometries by removing the neighbourless locations.
#' 
#' @param nbr an list of class "nb" generated by the poly2nb.ste function. This 
#'            is important because poly2nb.ste function sets the no.nbs attribute 
#'            that contains the names of the neighbourless locations.
#' @param pls **optional** a data frame or object of class "sf" with a polygons 
#'            geometry column and a Barcode column.Use it when you want to clean 
#'            the polygons data frame from the neighbourless locations.
#' @param inD **optional** a data frame with gene counts. Barcode must be 
#'            column names and genes in rows. Use it when you want to clean the 
#'            gene counts data frame from the neighbourless locations.
#' 
#' @export

clean.no.nbs <- function(nbr, pls, inD){
    
    # Check if nbr has the no.nbs attribute
    if(is.null(attr(nbr, "no.nbs"))){
        stop("The nb object provided to the nbr argument is missing the 'no.nbs'
             attribute. Make sure you used the poly2nb.ste function to generate
             an nb object that contains the neighbourless locations IDs as an 
             attribute")
    }
    
    # Get the neighbourless location Barcodes
    no.nbs <- attr(nbr, "no.nbs")
    
    # Remove them
    if(!missing(pls)){
        pls <- filter(pls, !Barcode %in% no.nbs)
        out <- pls
    } else if(!missing(inD)){
        inD <- select(inD, which(!colnames(inD) %in% no.nbs))
        out <- inD
    }

    return(out)
}