#' @name index_to_barcode
#' 
#' @description a function to translate indexes back to barcodes using the 
#'              dictionary list generated by get.dictionary function.
#' 
#' @param input the vector or data frame with a column of indexes to translate
#' @param dict_list the dictionary as generated by get.dictionary function
#' @param column default is NULL. Leave it NULL if you supply a vector. Otherwise
#'               provide a character string with the column name to translate. 
#'               If the input is vector (meaning is.vector(input) == TRUE) then
#'               the column argument is ignored.
#' 
#' @export

index_to_barcode <- function(input, dict_list, column = NULL){
  if (is.vector(input)) {
    input <- dict_list[["spots"]][match(input, rownames(dict_list[["spots"]]))]
    
  } else if (!is.vector(input) & !is.null(column)) {
    ## check that column exists
    if (!column %in% colnames(input)) {
      stop("Column name provided is not in input's column names.")
    }
    ## check if user wants to overwrite the column or not
    if (!.keepBoth) {
      col <- column
    } else {
      col <- "indexes"
    }
    
    input[,col] <- 
      dict_list[["spots"]][match(input[,column], rownames(dict_list[["spots"]]))]
    
  } else {
    stop("Please provide a valid combination of input and column arguments.
          If input is vector, leave column NULL. If input is a dataframe give
          a valid column name as argument to column.")
  }
  
  return(input)
}
