#' @name add.indexes
#' 
#' @description a function to use the dictionary to assign row and column 
#'              indexes to the gene expression matrix.
#'              
#' @param obs the gene expression matrix
#' @param dict_list a list. The dictionary list generated by get.dictionary function
#' @param row logical. do you want rownames to be replaced by indexes? 
#'            Default TRUE.
#' @param col logical. do you want colnames to be replaced by indexes? 
#'            Default TRUE.
#' 

add.indexes <- function(obs, dict_list, row = TRUE, col = TRUE) {
  ## Change row and column names in the obs object
  if (row) {
    rownames(obs) <-
      rownames(dict_list[["spots"]])[match(rownames(obs), dict_list[["spots"]])]
  }
  
  
  if (col) {
    colnames(obs) <-
      rownames(dict_list[["genes"]])[match(colnames(obs), dict_list[["genes"]])]
  }
  
  return(obs)
}

