######################################################-
# This is a script to launch the analysis of Spatial #
#   Transcriptomics data generated by 10X Genomics   #
#   Visium platform                                  #
#                                                    #
#' @author Eleftherios (Lefteris) Zormpas            #
#                                                    #
# This script is a replicate/ adaptation from an     #
#   original script written and provided by          #
#   Dr Rachel Queen Newcastle University             #
#   ---> give her the credit!                        #
######################################################-

#----------------------------------------------------#
## START OF SCRIPT ----
#----------------------------------------------------#

#----------------------------------------------------#
## 1. LOAD/ INSTALL PACKAGES ----
#----------------------------------------------------#
## 1.1 Bioconductor ----
pkgBio <- c("Spaniel", "scater", 
            "batchelor", "scran")

if (!require("BiocManager", quietly = TRUE))
  install.packages("BiocManager")

## Check if packages are installed and load them or install&load them if not.
pkg.check <- lapply(
  pkgBio, 
  FUN <- function(x) {
    if (!require(x, character.only = TRUE)) {
      BiocManager::install(x, update = FALSE)
      library(x, character.only = TRUE)
    } 
  }
)


## 1.2 Cran ----
pkgCRAN <- c("Seurat", "cowplot", 
             "RColorBrewer",
             "harmony", "dplyr", "spdep")

## Check if packages are installed and load them or install&load them if not.
pkg.check <- lapply(
  pkgCRAN, 
  FUN <- function(x) {
    if (!require(x, character.only = TRUE)) {
      install.packages(x, dependencies = TRUE)
      library(x, character.only = TRUE)
    }
  }
)

## 1.3 GitHub ----
pkgGit <- c("RachelQueen1/SCFunctionsV3")

if (!require("devtools", quietly = TRUE))
  install.packages("devtools")

pkg.check <- lapply(
  pkgGit, 
  FUN <- function(x) {
    pkg.name <- sub(".*/", "", x)
    if (!require(pkg.name, character.only = TRUE)) {
      devtools::install_git(paste0("https://github.com/", x))
      library(pkg.name, character.only = TRUE)
    }
  }
)

## 1.4 source scripts ----
source(file.path(projDir, "scripts/annotate.R"))
source(file.path(projDir, "scripts/read_biomart.R"))


#----------------------------------------------------#
## 2. CREATE/SET FOLDERS/PATHS ----
#----------------------------------------------------#
## Set file paths
projDir <- getwd()
inputDir <- file.path(projDir, "spaceranger_outs")
outputDir <- file.path(projDir, "rObjects/")
csvDir <- file.path(projDir, "csvFiles/")
graphDir <- file.path(projDir, "graphics_out/")
scriptsDir <- file.path(projDir, "scripts/")

## Check if inputDir/ outputDir/ csvDir exist and create them if not.
dirs <- c(inputDir, outputDir, csvDir, graphDir, scriptsDir)
dirCheck <- lapply(
  dirs,
  FUN = function(x){
    if(!dir.exists(x)) {
      dir.create(x, recursive = TRUE)
      print(paste0("Folder: ", x, " CREATED!"))
    } else {
      print(paste0("Folder: ", x, " EXISTS!"))
    }
  }
)
#----------------------------------------------------#
## 3. IMPORT FILES ----
#----------------------------------------------------#
## import all files, cluster replicates and save
sampleNames  <- list.files(path = inputDir)
for (sampleName in sampleNames){
  source(file.path(projDir, "scripts/1_ST_data_load.R"))
}

#----------------------------------------------------#
## 4. FIND MARKERS ----
#----------------------------------------------------#
source(file.path(projDir,"scripts/2_ST_data_Find.Markers.R"))


#----------------------------------------------------#
# END OF SCRIPT ----
#----------------------------------------------------#