#' Plot Gene Variance
#'
#' Visualizes the relationship between the mean and variance of log-expression
#' for specified genes in a SpatialFeatureExperiment.
#'
#' @param dec A list of modelled gene variances for each gene as generated by
#' the \code{modelGenevariance} function.
#' @param hvgs Character vector specifying the high variable genes (HVGs) to
#' plot as generated by the \code{getTopHighVarGenes}
#' function.
#' @param sample_id Logical or character vector specifying the sample IDs to
#' include in the plot. If TRUE (default), all samples are included.
#' @param ... Additional arguments to pass to the ggplot2 plotting functions.
#'
#' @return Returns a ggplot2 plot object representing the mean-variance
#' relationship of the specified genes.
#'
#' @details This function calculates the mean and variance of log-expression
#' for the specified high variance genes (HVGs) in a SpatialFeatureExperiment.
#' It then visualises this relationship using a scatter plot, with a trend line
#' fitted to the data.
#'
#' @seealso \code{\link[SpatialFeatureExperiment]{SpatialFeatureExperiment}},
#'  \code{\link[ggplot2]{ggplot}}
#'
#' @author Eleftherios (Lefteris) Zormpas
#'
#' @examples
#' \dontrun{
#' # hvgs : high variable genes as generated by the getTopHighVarGenes
#' plotGeneVariance(dec = modelled_var, hvgs = hvgs, sample_id = "JBO019")
#' }
#'
#' @keywords spatial visualisation ggplot2
#'
#' @importFrom ggplot2 ggplot geom_point geom_line scale_colour_manual
#' @importFrom ggplot2 facet_wrap labs theme_classic
#' @importFrom rlist list.rbind
#'
#' @rdname plotGeneVariance
#'
#' @export
plotGeneVariance <- function(dec, hvgs, sample_id = TRUE, ...) {
  ## Check arguments
  # stopifnot(is(msfe, "SpatialFeatureExperiment"))

  ## Select samples
  ids <- .int_getMSFEsmplID(msfe = dec, sample_id = sample_id)

  ## Get the curve fit and prepare the data frame
  fit_list <- lapply(ids, .int_getFit, dec = dec, hvgs = hvgs)
  fit_df <- rlist::list.rbind(fit_list)

  ## Plot the visualisation
  ggplot(data = fit_df,
         aes(x = data$mean, y = data$var, colour = data$topHVGs)) +
    geom_point() +
    geom_line(aes(y = data$trend), colour = "dodgerblue", linewidth = 1.5) +
    scale_colour_manual(values = c("black", "red")) +
    facet_wrap(~ sID) +
    labs(x = "Mean of log-expression",
         y = "Variance of log-expression",
         colour = "Top HVGs") +
    theme_classic()
}


.int_getFit <- function(id, dec, hvgs) {
  fit <- metadata(dec[[id]])
  fit_df <- data.frame(mean = fit$mean,
                       var = fit$var,
                       trend = fit$trend(fit$mean),
                       sID = id)

  fit_df <- fit_df %>%
    tibble::rownames_to_column(var = "row.names") %>%
    dplyr::mutate(topHVGs = ifelse(row.names %in% hvgs[[id]], TRUE, FALSE))
  # %>%
    # tibble::column_to_rownames("row.names")

  return(fit_df)
}
